### ISSUE TITLE
Error when trying to share a remote Tensor

### ISSUE THREAD

**Issue by codebecker** [OpenMined/PyGrid#377]
Trying to share a **remote** tensor (tensor pointer) results in a Error. The remote worker the tensor is located at shows multiple error messages listed below at Bob's log.

1. Start the gateway from the gateway folder in a own terminal with the following command:

`python gateway.py --start_local_db --port=5000`

2. Start three workers Alice, Bob, Charlie from the app/websocket folder each in a own terminal with the following command:

```
python websocket_app.py --start_local_db --id=alice --port=3000 --gateway_url=http://localhost:5000
python websocket_app.py --start_local_db --id=bob --port=3001 --gateway_url=http://localhost:5000
python websocket_app.py --start_local_db --id=charlie --port=3002 --gateway_url=http://localhost:5000
```

3. Run the following Script:
```
import torch as th
import syft as sy
import grid as gr

hook = sy.TorchHook(th)
gateway = gr.GridNetwork("http://localhost:5000")

alice = gr.WebsocketGridClient(hook, id="alice", address="http://localhost:3000")
alice.connect()

bob = gr.WebsocketGridClient(hook, id="bob", address="http://localhost:3001")
bob.connect()

charlie = gr.WebsocketGridClient(hook, id="charlie", address="http://localhost:3002")
charlie.connect()

# share a local tensor works
y = th.tensor([1,2,3,4]).share(alice, bob, crypto_provider = charlie) 

#sharing a remote tensor crashes
x = th.tensor([1,2,3,4]).send(bob).share(alice, bob, crypto_provider = charlie)
```
**Logs and Errors**

3.1 script's log:
```
Websocket connection closed (worker: bob)
Created new websocket connection
Traceback (most recent call last):
  File "[...]PyGrid/playground/tut1.py", line 20, in <module>
    x = x.share(alice, bob, crypto_provider = charlie)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 762, in share
    *owners, field=field, crypto_provider=crypto_provider, **kwargs
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/generic/pointers/pointer_tensor.py", line 368, in share
    response = self.owner.send_command(self.location, command)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 489, in send_command
    ret_val = self.send_msg(Operation(message, return_ids), location=recipient)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 258, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/websocket_client.py", line 98, in _recv_msg
    "Websocket connection closed and creation of new connection failed."
RuntimeError: Websocket connection closed and creation of new connection failed.`
```

3.2 Gateway's Log:
```
WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Nov/2019 13:05:07] "POST /join HTTP/1.1" 409 -
INFO:werkzeug:127.0.0.1 - - [07/Nov/2019 13:06:02] "POST /join HTTP/1.1" 409 -
INFO:werkzeug:127.0.0.1 - - [07/Nov/2019 13:06:08] "POST /join HTTP/1.1" 200 -
```

3.3 Alice's Log:
```
#EMPTY 
```

3.4 Bob's Log:
```
Worker bob couldn't recognize worker alice
Worker bob couldn't recognize worker charlie
Worker me couldn't recognize worker alice
Worker me couldn't recognize worker alice
Traceback (most recent call last):
  File "[...]pysyft/venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 60, in socket_api
    response = route_requests(message)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 40, in route_requests
    return forward_binary_message(message)
  File "[...]PyGrid/app/websocket/app/main/auth/__init__.py", line 60, in wrapped
    return f(*args, **kwargs)
  File "[...]PyGrid/app/websocket/app/main/events/syft_events.py", line 24, in forward_binary_message
    decoded_response = current_user.worker._recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 10, in _recv_msg
    return self.recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 292, in recv_msg
    response = self._message_router[msg_type](contents)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 412, in execute_command
    response = getattr(_self, command_name)(*args, **kwargs)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 770, in share
    .init_shares(*owners)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/additive_shared.py", line 176, in init_shares
    share_ptr = share.send(owner, **no_wrap)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 380, in send
    garbage_collect_data=garbage_collect_data,
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 378, in send
    self.send_obj(obj, worker)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 582, in send_obj
    return self.send_msg(ObjectMessage(obj), location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 258, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
AttributeError: 'str' object has no attribute '_recv_msg'
2019-11-07T12:08:03Z {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '39122', 'HTTP_HOST': 'localhost:3001', (hidden keys: 25)} failed with AttributeError

Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/generic/pointers/object_pointer.py", line 341, in __del__
    self.owner.send_msg(ForceObjectDeleteMessage(self.id_at_location), self.location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 258, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
AttributeError: 'str' object has no attribute '_recv_msg'
Worker bob couldn't recognize worker alice
Worker bob couldn't recognize worker charlie
Worker me couldn't recognize worker alice
Worker me couldn't recognize worker alice
Traceback (most recent call last):
  File "[...]pysyft/venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 60, in socket_api
    response = route_requests(message)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 40, in route_requests
    return forward_binary_message(message)
  File "[...]PyGrid/app/websocket/app/main/auth/__init__.py", line 60, in wrapped
    return f(*args, **kwargs)
  File "[...]PyGrid/app/websocket/app/main/events/syft_events.py", line 24, in forward_binary_message
    decoded_response = current_user.worker._recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 10, in _recv_msg
    return self.recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 292, in recv_msg
    response = self._message_router[msg_type](contents)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 412, in execute_command
    response = getattr(_self, command_name)(*args, **kwargs)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 770, in share
    .init_shares(*owners)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/additive_shared.py", line 176, in init_shares
    share_ptr = share.send(owner, **no_wrap)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 380, in send
    garbage_collect_data=garbage_collect_data,
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 378, in send
    self.send_obj(obj, worker)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 582, in send_obj
    return self.send_msg(ObjectMessage(obj), location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 258, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
AttributeError: 'str' object has no attribute '_recv_msg'
2019-11-07T12:08:03Z {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '39128', 'HTTP_HOST': 'localhost:3001', (hidden keys: 25)} failed with AttributeError

Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/generic/pointers/object_pointer.py", line 341, in __del__
    self.owner.send_msg(ForceObjectDeleteMessage(self.id_at_location), self.location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 258, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
AttributeError: 'str' object has no attribute '_recv_msg'

```

3.5 Charlie's Log:
```
#EMPTY
```

**Expected behavior**
The tensor should be shared among the specified workers and calculations should be possible with it.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 19.1 Cinnamon

I'm not sure what else could be helpful but here is my grid and syft version:
```
Package              Version         
-------------------- ----------------
grid                 0.1.0.0a1.dev402
syft                 0.2.0a2         
```

**Comment by codebecker** [comment]
**NOTE:** This error is specificity about trying to share a tensor pointer. Sharing a local tensor works fine:

**Comment by codebecker** [comment]
**Edit**: Also all the workers know each other: 
```import torch as th
import syft as sy
import grid as gr

hook = sy.TorchHook(th)
gateway = gr.GridNetwork("http://localhost:5000")

alice = gr.WebsocketGridClient(hook, id="alice", address="http://localhost:3000")
alice.connect()

bob = gr.WebsocketGridClient(hook, id="bob", address="http://localhost:3001")
bob.connect()

charlie = gr.WebsocketGridClient(hook, id="charlie", address="http://localhost:3002")
charlie.connect()

print(alice._known_workers)
print(bob._known_workers)
print(charlie._known_workers)
```
Outputs:
```
{'me': <VirtualWorker id:me #objects:0>, 'alice': Grid Worker < id: alice >, 'bob': Grid Worker < id: bob >, 'charlie': Grid Worker < id: charlie >}
{'me': <VirtualWorker id:me #objects:0>, 'alice': Grid Worker < id: alice >, 'bob': Grid Worker < id: bob >, 'charlie': Grid Worker < id: charlie >}
{'me': <VirtualWorker id:me #objects:0>, 'alice': Grid Worker < id: alice >, 'bob': Grid Worker < id: bob >, 'charlie': Grid Worker < id: charlie >}
```

**Comment by IonesioJunior** [comment]
Hello @codebecker !

First of all, awesome report!

About your problem: you need to establish a connection between nodes. They know each other, but they don't have an independent connection between each other (Bob knows who is Alice and Charlie, but he doesn't know how to exchange messages with them).

Hopefully, To fix your problem you only need to add `gr.utils.connect_all_nodes([alice,bob,charlie])`

PS: To simplify our code, we don't need to call `connect` method or define an id to the nodes. (It will be defined automatically).

The fixed code:
```
import torch as th
import syft as sy
import grid as gr

hook = sy.TorchHook(th)
gateway = gr.GridNetwork("http://localhost:5000")

alice = gr.WebsocketGridClient(hook, address="ws://localhost:3000")
bob = gr.WebsocketGridClient(hook, address="ws://localhost:3001")
charlie = gr.WebsocketGridClient(hook, address="ws://localhost:3002")

gr.utils.connect_all_nodes([alice,bob,charlie])

# share a local tensor works
y = th.tensor([1,2,3,4]).share(alice, bob, crypto_provider = charlie) 

#sharing a remote tensor crashes
x = th.tensor([1,2,3,4]).send(bob).share(alice, bob, crypto_provider = charlie)
```

**Comment by codebecker** [comment]
Thank you very much for your help and the optimization in my code. The code i used here is copied from the Tutorials of the gitrepo.
