### ISSUE TITLE
Calling fix_precision() on a remote Tensor crashes

### ISSUE THREAD

**Issue by codebecker** [OpenMined/PyGrid#379]
**Describe the bug**
While trying to secure aggregate two models calling fix_precision on a remote model crashed. I could reproduce the error by calling fix_precision on a remote tensor with the following code.

**To Reproduce**
Start Gateway and Worker on your local machine each in a own cmd:
`python gateway.py --start_local_db --port=5000`
`python websocket_app.py --start_local_db --id=alice --port=3000 --gateway_url=http://localhost:5000`

Run the following script trying to make a remote tensor fix precision
```
import torch as th
import syft as sy
import grid as gr

hook = sy.TorchHook(th)
gateway = gr.GridNetwork("http://localhost:5000")

alice = gr.WebsocketGridClient(hook, address="ws://localhost:3000")

y = th.tensor([1.,2.,3.,4.]).send(alice).fix_precision()

```

**Logs and Error**
Script Log:
```
Websocket connection closed (worker: alice)
Created new websocket connection
Traceback (most recent call last):
  File "[...]PyGrid/playground/tut1.py", line 14, in <module>
    y = th.tensor([1.,2.,3.,4.]).send(alice).fix_precision()
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 653, in fix_prec
    self.child = self.child.fix_prec(*args, **kwargs)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/generic/pointers/pointer_tensor.py", line 334, in fix_prec
    response = self.owner.send_command(self.location, command)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 489, in send_command
    ret_val = self.send_msg(Operation(message, return_ids), location=recipient)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 258, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/websocket_client.py", line 98, in _recv_msg
    "Websocket connection closed and creation of new connection failed."
RuntimeError: Websocket connection closed and creation of new connection failed.
Exception ignored in: <bound method ObjectPointer.__del__ of [PointerTensor | me:51780967838 -> alice:36494535748]>
Traceback (most recent call last):
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/generic/pointers/object_pointer.py", line 341, in __del__
    self.owner.send_msg(ForceObjectDeleteMessage(self.id_at_location), self.location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 258, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/websocket_client.py", line 86, in _recv_msg
    response = self._forward_to_websocket_server_worker(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/grid/websocket_client.py", line 208, in _forward_to_websocket_server_worker
    response = self.ws.recv()
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "[...]pysyft/venv/lib/python3.6/site-packages/websocket/_socket.py", line 115, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

Process finished with exit code 1
```

Worker Alice Log:
```
Worker alice couldn't recognize worker me
Traceback (most recent call last):
  File "[...]pysyft/venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 60, in socket_api
    response = route_requests(message)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 40, in route_requests
    return forward_binary_message(message)
  File "[...]PyGrid/app/websocket/app/main/auth/__init__.py", line 60, in wrapped
    return f(*args, **kwargs)
  File "[...]PyGrid/app/websocket/app/main/events/syft_events.py", line 24, in forward_binary_message
    decoded_response = current_user.worker._recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 10, in _recv_msg
    return self.recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 292, in recv_msg
    response = self._message_router[msg_type](contents)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 412, in execute_command
    response = getattr(_self, command_name)(*args, **kwargs)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 704, in fix_prec
    fpt_tensor = fpt_tensor.wrap()
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/generic/tensor.py", line 49, in wrap
    self.owner.register_obj(wrapper, obj_id=self.id)
AttributeError: 'str' object has no attribute 'register_obj'
2019-11-08T08:54:29Z {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '36726', 'HTTP_HOST': 'localhost:3000', (hidden keys: 25)} failed with AttributeError

Worker alice couldn't recognize worker me
Traceback (most recent call last):
  File "[...]pysyft/venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "[...]pysyft/venv/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "[...]pysyft/venv/lib/python3.6/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 60, in socket_api
    response = route_requests(message)
  File "[...]PyGrid/app/websocket/app/main/events/__init__.py", line 40, in route_requests
    return forward_binary_message(message)
  File "[...]PyGrid/app/websocket/app/main/auth/__init__.py", line 60, in wrapped
    return f(*args, **kwargs)
  File "[...]PyGrid/app/websocket/app/main/events/syft_events.py", line 24, in forward_binary_message
    decoded_response = current_user.worker._recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/virtual.py", line 10, in _recv_msg
    return self.recv_msg(message)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 292, in recv_msg
    response = self._message_router[msg_type](contents)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 412, in execute_command
    response = getattr(_self, command_name)(*args, **kwargs)
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 704, in fix_prec
    fpt_tensor = fpt_tensor.wrap()
  File "[...]pysyft/venv/lib/python3.6/site-packages/syft/generic/tensor.py", line 49, in wrap
    self.owner.register_obj(wrapper, obj_id=self.id)
AttributeError: 'str' object has no attribute 'register_obj'
2019-11-08T08:54:29Z {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '36728', 'HTTP_HOST': 'localhost:3000', (hidden keys: 25)} failed with AttributeError

```
**Expected behavior**
The tensor tensor should be fixed precision and thus be shared among other workers. This is needed for secure aggregation with shared gradients.

**Desktop:**
 - OS: Mint 17.1

I'm not sure what else could be helpful but here is my grid and syft version:

Package              Version         
-------------------- ----------------
grid                 0.1.0.0a1.dev402
syft                 0.2.0a2

**Comment by IonesioJunior** [comment]
Hello @codebecker, thank you for reporting this issue!
I'll debug it as soon as possible.

**Comment by gantir** [comment]
@IonesioJunior ,
Did you get a chance to look at it? I can look into it.

**Comment by IonesioJunior** [comment]
Hello @gantir!
Yeah, please! I would appreciate if you can look into it! :heart:

**Comment by gantir** [comment]
> Hello @gantir!
> Yeah, please! I would appreciate if you can look into it!

Cool. Working on this

**Comment by H4LL** [comment]
Did you manage to find anything? I also have this issue

**Comment by gantir** [comment]
@H4LL , Not made much progress over the holidays.

**Comment by IonesioJunior** [comment]
Solved by  @bobsonlin26's  [PR](https://github.com/OpenMined/GridNode/pull/7) ?
