### ISSUE TITLE
Running a worker container fails (Update Torch Version)?

### ISSUE THREAD

**Issue by codebecker** [OpenMined/PyGrid#385]
**Describe the bug**
The app container build from PyGrid Repo fails with the following error:
`AttributeError: module 'torch._C' has no attribute 'Function'`

**To Reproduce**
0. At first a a gateway container must be up and running to start a worker:
```
docker build -t gateway ./gateway/  # Build gateway image
docker run -e PORT=5000 -e DATABASE_URL=sqlite:///databasegateway.db --network host gateway #starting gateway
```

1. Pull PyGrid repo and build container by:
`docker build -t node ./app/websocket/`
2. Run container with:
`docker run -e GRID_NETWORK_URL=http://localhost:5000 -e ID=Bob -e ADDRESS==http://localhost:3000/ -e DATABASE_URL=sqlite:///databaseBob.db -e PORT=3000 -network host node`
3. See errors throwen when starting the container
```
[2019-11-11 07:58:52 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-11-11 07:58:52 +0000] [1] [INFO] Listening at: http://127.0.0.1:8000 (1)
[2019-11-11 07:58:52 +0000] [1] [INFO] Using worker: flask_sockets.worker
[2019-11-11 07:58:52 +0000] [8] [INFO] Booting worker with pid: 8
[2019-11-11 07:58:53 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/websocket_app.py", line 97, in <module>
    app = create_app(node_id, debug=False)
  File "/app/app/__init__.py", line 19, in create_app
    from .main import html, ws, db, hook, local_worker, auth
  File "/app/app/main/__init__.py", line 3, in <module>
    import syft as sy
  File "/usr/local/lib/python3.7/site-packages/syft/__init__.py", line 76, in <module>
    from syft import serde
  File "/usr/local/lib/python3.7/site-packages/syft/serde/__init__.py", line 1, in <module>
    from syft.serde.serde import *
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 80, in <module>
    from syft.serde.torch_serde import MAP_TORCH_SIMPLIFIERS_AND_DETAILERS
  File "/usr/local/lib/python3.7/site-packages/syft/serde/torch_serde.py", line 297, in <module>
    torch._C.Function: (_simplify_script_module, _detail_script_module),
AttributeError: module 'torch._C' has no attribute 'Function'
[2019-11-11 07:58:53 +0000] [8] [INFO] Worker exiting (pid: 8)
[2019-11-11 07:58:53 +0000] [1] [INFO] Shutting down: Master
[2019-11-11 07:58:53 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Expected behavior**
The container should start and a worker should be available at port 3000.

**Workaround (Fix?)**
I fixed this error with a workaround by updating the torch version in the requirements.txt  `PyGrid/app/websocket/requirements.txt ` used to build the container.  I don't know which version suites best for PyGrid otherwise I would setup a pull request.

```
#https://files.pythonhosted.org/packages/4e/ba/d78f35357995297206790fe1af8688bc0403828c90f8e99190035196d56e/torch-1.0.1-cp37-cp37m-manylinux1_x86_64.whl; sys_platform == "linux"
#https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-win_amd64.whl; sys_platform == "windows"
#torch; sys_platform == "darwin"
torch==1.3.0
```

**Comment by IonesioJunior** [comment]
Hello @codebecker, Thanks for reporting this :heart:!
Could you submit a PR fixing it?
Should I assign this issue to you?
