### ISSUE TITLE
Setting verbose=True when creating the local_worker leads to a later failure

### ISSUE THREAD

**Issue by luispd** [OpenMined/PyGrid#451]
**Describe the bug**
Setting `verbose=True` when creating the local_worker leads to a later failure when performing the calculation of max() (and perhaps other functions) over an additive sharing tensor.

**To Reproduce**
1. Go to app/websocket/app/main/__init__.py and introduce the following change
```
 # Global variables must be initialized here.
 hook = sy.TorchHook(th)
-local_worker = sy.VirtualWorker(hook, auto_add=False)
+local_worker = sy.VirtualWorker(hook, auto_add=False, verbose=True)
 hook.local_worker.is_client_worker = False

 html = Blueprint(r"html", __name__)
```
2. Start the servers:
python websocket_app.py --port=3000 --id=alice
python websocket_app.py --port=3001 --id=bob
python websocket_app.py --port=3002 --id=crypto

3. Run this script:
```
import syft as sy
import torch
from syft.workers.node_client import NodeClient

hook = sy.TorchHook(torch)

alice = NodeClient(hook, id="alice", address="http://localhost:3000")
bob = NodeClient(hook, id="bob", address="http://localhost:3001")
crypto = NodeClient(hook, id="crypto", address="http://localhost:3002")

my_grid = sy.PrivateGridNetwork(alice,bob,crypto)

x_shr = torch.tensor([1,2,3,4,5,6]).share(alice,bob,crypto_provider=crypto)

res = x_shr.max()

print(res.get())
```

See this error in alice:
```
Traceback (most recent call last):
  File "C:\Users\llpd\PycharmProjects\PyGrid\venv\lib\site-packages\gevent\pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "C:\Users\llpd\PycharmProjects\PyGrid\venv\lib\site-packages\geventwebsocket\handler.py", line 75, in run_application
    self.run_websocket()
  File "C:\Users\llpd\PycharmProjects\PyGrid\venv\lib\site-packages\geventwebsocket\handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "C:\Users\llpd\PycharmProjects\PyGrid\venv\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\llpd\PycharmProjects\PyGrid\venv\lib\site-packages\flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "C:\Users\llpd\PycharmProjects\PyGrid\app\websocket\app\main\events\__init__.py", line 57, in socket_api
    response = route_requests(message)
  File "C:\Users\llpd\PycharmProjects\PyGrid\app\websocket\app\main\events\__init__.py", line 37, in route_requests
    return forward_binary_message(message)
  File "C:\Users\llpd\PycharmProjects\PyGrid\app\websocket\app\main\auth\__init__.py", line 60, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\llpd\PycharmProjects\PyGrid\app\websocket\app\main\events\syft_events.py", line 27, in forward_binary_message
    decoded_response = current_user.worker._recv_msg(message)
  File "c:\users\llpd\pycharmprojects\pygrid\venv\src\syft\syft\workers\virtual.py", line 10, in _recv_msg
    return self.recv_msg(message)
  File "c:\users\llpd\pycharmprojects\pygrid\venv\src\syft\syft\workers\base.py", line 307, in recv_msg
    print(f"worker {self} received {type(msg).__name__} {msg.contents}")
  File "C:\Users\llpd\PycharmProjects\PyGrid\venv\lib\site-packages\torch\tensor.py", line 409, in __format__
    return self.item().__format__(format_spec)
  File "c:\users\llpd\pycharmprojects\pygrid\venv\src\syft\syft\generic\frameworks\hook\trace.py", line 83, in trace_wrapper
    response = func(*args, **kwargs)
  File "c:\users\llpd\pycharmprojects\pygrid\venv\src\syft\syft\generic\frameworks\hook\hook.py", line 477, in overloaded_native_method
    response = method(*new_args, **new_kwargs)
  File "c:\users\llpd\pycharmprojects\pygrid\venv\src\syft\syft\frameworks\torch\hook\hook.py", line 509, in overloaded_attr
    results[k] = v.__getattribute__(attr)(*dispatch(new_args, k), **new_kwargs)
  File "c:\users\llpd\pycharmprojects\pygrid\venv\src\syft\syft\generic\pointers\pointer_tensor.py", line 442, in item
    'Error, Please consider calling ".get" method instead of ".item" method, '
RuntimeError: Error, Please consider calling ".get" method instead of ".item" method, so you can be safely getting the item you need.
2020-02-12T16:19:33Z {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '63424', 'HTTP_HOST': 'localhost:3000', (hidden keys: 25)} failed with RuntimeError
```
And see this error in the console where the script was run:
`Websocket connection closed (worker: alice)`

**Expected behavior**
The calculation succeeds and tensor([6]) is displayed in the console.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by hericlesme** [comment]
Hello @luispd, thank you for reporting this issue! I'll debug it ASAP! :wink:

**Comment by hericlesme** [comment]
Probably the problem is in the PySyft virtual worker. The same issue was reported for local workers, I think it's the same problem. https://github.com/OpenMined/PySyft/issues/2279

**Comment by IonesioJunior** [comment]
This issue was moved to the PySyft repository.
