### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by DanielMorales9** [OpenMined/PyGrid#490]
I get this error  while ``pip installing grid@git+https://github.com/OpenMined/PyGrid.git@dev``
```
Collecting grid@ git+https://github.com/OpenMined/PyGrid.git@dev
Cloning https://github.com/OpenMined/PyGrid.git (to revision dev) to /tmp/pip-install-ri8il30i/grid
  Running command git clone -q https://github.com/OpenMined/PyGrid.git /tmp/pip-install-ri8il30i/grid
    ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ri8il30i/grid/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ri8il30i/grid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ri8il30i/grid/pip-egg-info
cwd: /tmp/pip-install-ri8il30i/grid/
Complete output (5 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/lib/python3.7/tokenize.py", line 447, in open
buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ri8il30i/grid/setup.py'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by joaolcaas** [comment]
Hey @DanielMorales9 , this repository is not a installable package anymore. To install the dependencies that this repo need , you can just install requirements.txt

**Comment by DanielMorales9** [comment]
Hi @joaolcaas, Thanks a lot.
