### ISSUE TITLE
Broken Tutorials / Websocket Fails to Make a Connection

### ISSUE THREAD

**Issue by eric-yates** [OpenMined/PyGrid#560]
**Describe the bug**
None of the Grid tutorials work any longer, at least on my system. It appears that websocket fails to makes a connection. 

**To Reproduce**
1. Add domain names (gateway, bob, etc) to /etc/hosts
2. Clone PyGrid and run `docker-compose up`
3. Create a Conda env from "PyGrid/requirements.txt"
4. Open notebook "PyGrid/examples/Part 1 - Launch a PyGrid Node Locally" with Conda env
5. Run the cell `x = th.tensor([1,2,3,4]).send(worker)`
6. See errors at bottom of this issue

This seems to happen anywhere when sending data to a worker. It has happened in other tutorials too, like the grid tutorials in PySyft.

**Expected behavior**
The tensor is sent to the worker called Bob.

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.4

**Additional context**

Tutorial logs
```
Websocket connection closed (worker: Bob)
Created new websocket connection

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-5521f32c7dc0> in <module>
----> 1 x = th.tensor([1,2,3,4]).send(worker)
      2 x

~/anaconda3/envs/gridEnv/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in send(self, inplace, user, local_autograd, preinitialize_grad, no_wrap, garbage_collect_data, *location)
    417                 local_autograd=local_autograd,
    418                 preinitialize_grad=preinitialize_grad,
--> 419                 garbage_collect_data=garbage_collect_data,
    420             )
    421 

~/anaconda3/envs/gridEnv/lib/python3.7/site-packages/syft/workers/base.py in send(self, obj, workers, ptr_id, garbage_collect_data, create_pointer, **kwargs)
    385 
    386         # Send the object
--> 387         self.send_obj(obj, worker)
    388 
    389         # If we don't need to create the pointer

~/anaconda3/envs/gridEnv/lib/python3.7/site-packages/syft/workers/base.py in send_obj(self, obj, location)
    678                 receive the object.
    679         """
--> 680         return self.send_msg(ObjectMessage(obj), location)
    681 
    682     def request_obj(

~/anaconda3/envs/gridEnv/lib/python3.7/site-packages/syft/workers/base.py in send_msg(self, message, location)
    285 
    286         # Step 2: send the message and wait for a response
--> 287         bin_response = self._send_msg(bin_message, location)
    288 
    289         # Step 3: deserialize the response

~/anaconda3/envs/gridEnv/lib/python3.7/site-packages/syft/workers/virtual.py in _send_msg(self, message, location)
     13             sleep(self.message_pending_time)
     14 
---> 15         return location._recv_msg(message)
     16 
     17     def _recv_msg(self, message: bin) -> bin:

~/anaconda3/envs/gridEnv/lib/python3.7/site-packages/syft/workers/websocket_client.py in _recv_msg(self, message)
    103             if not self.ws.connected:
    104                 raise RuntimeError(
--> 105                     "Websocket connection closed and creation of new connection failed."
    106                 )
    107         return response

RuntimeError: Websocket connection closed and creation of new connection failed.
```
Docker logs
```
bob_1      | Traceback (most recent call last):
bob_1      |   File "/root/.local/lib/python3.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
bob_1      |     self.run_application()
bob_1      |   File "/root/.local/lib/python3.7/site-packages/geventwebsocket/handler.py", line 75, in run_application
bob_1      |     self.run_websocket()
bob_1      |   File "/root/.local/lib/python3.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
bob_1      |     list(self.application(self.environ, lambda s, h, e=None: []))
bob_1      |   File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
bob_1      |     return self.wsgi_app(environ, start_response)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/flask_sockets.py", line 45, in __call__
bob_1      |     handler(environment, **values)
bob_1      |   File "/app/app/main/events/__init__.py", line 57, in socket_api
bob_1      |     response = route_requests(message)
bob_1      |   File "/app/app/main/events/__init__.py", line 37, in route_requests
bob_1      |     return forward_binary_message(message)
bob_1      |   File "/app/app/main/auth/__init__.py", line 60, in wrapped
bob_1      |     return f(*args, **kwargs)
bob_1      |   File "/app/app/main/events/syft_events.py", line 27, in forward_binary_message
bob_1      |     decoded_response = current_user.worker._recv_msg(message)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/workers/virtual.py", line 19, in _recv_msg
bob_1      |     return self.recv_msg(message)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/workers/base.py", line 311, in recv_msg
bob_1      |     msg = sy.serde.deserialize(bin_message, worker=self)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/serde/serde.py", line 69, in deserialize
bob_1      |     return strategy(binary, worker)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 384, in deserialize
bob_1      |     return _deserialize_msgpack_simple(simple_objects, worker)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 375, in _deserialize_msgpack_simple
bob_1      |     return _detail(worker, simple_objects)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 501, in _detail
bob_1      |     val = detailers[obj[0]](worker, obj[1], **kwargs)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/messaging/message.py", line 252, in detail
bob_1      |     return ObjectMessage(sy.serde.msgpack.serde._detail(worker, msg_tuple[0]))
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 501, in _detail
bob_1      |     val = detailers[obj[0]](worker, obj[1], **kwargs)
bob_1      |   File "/root/.local/lib/python3.7/site-packages/syft/serde/msgpack/torch_serde.py", line 192, in _detail_torch_tensor
bob_1      |     ) = tensor_tuple
bob_1      | ValueError: not enough values to unpack (expected 9, got 7)
bob_1      | 2020-05-10T05:16:09Z {'REMOTE_ADDR': '172.18.0.1', 'REMOTE_PORT': '56848', 'HTTP_HOST': 'localhost:3000', (hidden keys: 26)} failed with ValueError
```

**Comment by eric-yates** [comment]
Closed due to duplicate issue with #543
